version: '3.8'
services:
  backend:
    build: ./backend
    container_name: detectron2_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/workspace
      - ./images:/workspace/images
      - ./outputs:/workspace/outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always