version: '3.8'

services:
  backend:
    build: ./backend
    container_name: detectron2_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/workspace:cached
      - ./images:/workspace/images:cached
      - ./outputs:/workspace/outputs
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "16g"
    tmpfs:
      - /dev/shm:size=16g
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
